source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RNSync_Example', :exclusive => true do
  pod 'RNSync', :path => '../'
end

target 'RNSync_Tests', :exclusive => true do
  pod 'RNSync', :path => '../'

  
end
